name: CI

on:
  push:
    branches:
      - main
      - 'release/*'
    tags:
      - 'v*'

jobs:
  lint:
    runs-on: ubuntu-latest
    if: github.ref_type == 'branch'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install uv
      - run: uv sync --dev
      - run: uv run ruff check codesnap

  test:
    runs-on: ubuntu-latest
    if: github.ref_type == 'branch'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install uv
      - run: uv sync --dev
      - run: uv run pytest

  build:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install uv
      - run: uv build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref_type == 'tag'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install uv
      - run: uv add --dev twine
      - name: Publish to PyPI or TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD_TESTPYPI: ${{ secrets.TWINE_PASSWORD_TESTPYPI }}
          TWINE_PASSWORD_PYPI: ${{ secrets.TWINE_PASSWORD_PYPI }}
        run: |
          if [[ "${GITHUB_REF_NAME}" == *"-test" ]]; then
            export TWINE_PASSWORD=$TWINE_PASSWORD_TESTPYPI
            uv run twine upload --non-interactive --repository-url https://test.pypi.org/legacy/ dist/*
          else
            export TWINE_PASSWORD=$TWINE_PASSWORD_PYPI
            uv run twine upload --non-interactive dist/*
          fi